version: '2.4'
services:
  ors-app:
    container_name: ors-app
    ports:
      - 8080:8080
      - 9001:9001
    image: openrouteservice/openrouteservice:latest
    build:
      context: ../
      args:
        ORS_CONFIG: C:/ors-config/ors-config.json
#        OSM_FILE: ./openrouteservice/src/main/files/heidelberg.osm.gz
#        OSM_FILE: "C:/Users/laure/stack/Gopa/usecase_OTP_Project/03_Croatia/current_capital_file.osm.pbf"
#        OSM_FILE: "C:/Users/laure/stack/Gopa/usecase_OTP_Project/04_Spain/current_capital_file.osm.pbf"
        OSM_FILE: "C:/Users/laure/stack/Gopa/usecase_OTP_Project/05_Finland/current_capital_file.osm.pbf"

    user: "${ORS_UID:-0}:${ORS_GID:-0}"
    volumes:
      - ./graphs:/ors-core/data/graphs
      - ./elevation_cache:/ors-core/data/elevation_cache
      - ./logs/ors:/var/log/ors
      - ./logs/tomcat:/usr/local/tomcat/logs
      - C:/ors-config:/ors-conf
      - C:/Users/laure/stack/Gopa/usecase_OTP_Project/05_Finland/current_capital_file.osm.pbf:/ors-core/data/osm_file.pbf
    environment:
      - BUILD_GRAPHS=True  # Forces the container to rebuild the graphs, e.g. when PBF is changed
      - "JAVA_OPTS=-Djava.awt.headless=true -server -XX:TargetSurvivorRatio=75 -XX:SurvivorRatio=64 -XX:MaxTenuringThreshold=3 -XX:+UseG1GC -XX:+ScavengeBeforeFullGC -XX:ParallelGCThreads=4 -Xms1g -Xmx2g"
      - "CATALINA_OPTS=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9001 -Dcom.sun.management.jmxremote.rmi.port=9001 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=localhost"