  CREATE TABLE AIS_RAW 
   (LOADING_DATE TIMESTAMP (6) NOT NULL ENABLE, 
	MMSI VARCHAR2(32 BYTE) NOT NULL ENABLE, 
	TSTAMP VARCHAR2(32 BYTE) NOT NULL ENABLE, 
	LATITUDE VARCHAR2(32 BYTE) NOT NULL ENABLE, 
	LONGITUDE VARCHAR2(32 BYTE) NOT NULL ENABLE, 
	COG VARCHAR2(32 BYTE) NOT NULL ENABLE, 
	SOG VARCHAR2(32 BYTE) NOT NULL ENABLE, 
	HEADING VARCHAR2(32 BYTE) NOT NULL ENABLE, 
	NAVSTAT VARCHAR2(32 BYTE) NOT NULL ENABLE, 
	IMO VARCHAR2(32 BYTE) NOT NULL ENABLE, 
	NAME VARCHAR2(32 BYTE) NOT NULL ENABLE, 
	CALLSIGN VARCHAR2(32 BYTE), 
	TYPE VARCHAR2(32 BYTE) NOT NULL ENABLE, 
	A VARCHAR2(32 BYTE) NOT NULL ENABLE, 
	B VARCHAR2(32 BYTE) NOT NULL ENABLE, 
	C VARCHAR2(32 BYTE) NOT NULL ENABLE, 
	D VARCHAR2(32 BYTE) NOT NULL ENABLE, 
	DRAUGHT VARCHAR2(32 BYTE) NOT NULL ENABLE, 
	DEST VARCHAR2(32 BYTE), 
	ETA VARCHAR2(32 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT PK_AIS_RAW PRIMARY KEY (MMSI, TSTAMP, LOADING_DATE);
	 

  CREATE TABLE SHIP_INFO 
   (MMSI VARCHAR2(32 BYTE) NOT NULL ENABLE, 
	IMO VARCHAR2(32 BYTE) NOT NULL ENABLE, 
	NAME VARCHAR2(128 BYTE) NOT NULL ENABLE, 
	TYPE VARCHAR2(128 BYTE) NOT NULL ENABLE, 
	FLAG VARCHAR2(32 BYTE) NOT NULL ENABLE, 
	GROSS_TONNAGE VARCHAR2(32 BYTE) NOT NULL ENABLE, 
	DEADWEIGHT VARCHAR2(32 BYTE) NOT NULL ENABLE, 
	LENGTH VARCHAR2(32 BYTE) NOT NULL ENABLE, 
	WIDTH VARCHAR2(32 BYTE) NOT NULL ENABLE, 
	YEAR VARCHAR2(32 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT PK_SHIP_INFO PRIMARY KEY (IMO);

  CREATE UNIQUE INDEX AK_SHIP_INFO ON SHIP_INFO (MMSI);	 